// <auto-generated />
using System;
using DrugsBot.Infrastructure.Dal.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrugsBot.Infrastructure.Migrations
{
    [DbContext(typeof(DrugBotDbContext))]
    partial class DrugBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrugsBot.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.Drug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCodeId");

                    b.ToTable("Drug", (string)null);
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.DrugItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Count")
                        .HasColumnType("float");

                    b.Property<Guid>("DrugId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DrugStoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DrugStoreId");

                    b.HasIndex("DrugId", "DrugStoreId")
                        .IsUnique();

                    b.ToTable("DrugItem", (string)null);
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.DrugStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DrugNetwork")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DrugNetwork", "Number")
                        .IsUnique();

                    b.ToTable("DrugStore", (string)null);
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.FavoriteDrug", b =>
                {
                    b.Property<Guid>("DrugId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DrugStoreId")
                        .HasColumnType("uuid");

                    b.HasKey("DrugId", "ProfileId");

                    b.HasIndex("DrugStoreId");

                    b.HasIndex("ProfileId");

                    b.ToTable("FavoriteDrug", (string)null);
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.Drug", b =>
                {
                    b.HasOne("DrugsBot.Domain.Entities.Country", "Country")
                        .WithMany("Drugs")
                        .HasForeignKey("CountryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.DrugItem", b =>
                {
                    b.HasOne("DrugsBot.Domain.Entities.Drug", "Drug")
                        .WithMany("DrugItems")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrugsBot.Domain.Entities.DrugStore", "DrugStore")
                        .WithMany("DrugItems")
                        .HasForeignKey("DrugStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("DrugStore");
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.DrugStore", b =>
                {
                    b.OwnsOne("DrugsBot.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("DrugStoreId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("DrugStoreId");

                            b1.ToTable("DrugStore");

                            b1.WithOwner()
                                .HasForeignKey("DrugStoreId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.FavoriteDrug", b =>
                {
                    b.HasOne("DrugsBot.Domain.Entities.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrugsBot.Domain.Entities.DrugStore", "DrugStore")
                        .WithMany()
                        .HasForeignKey("DrugStoreId");

                    b.HasOne("DrugsBot.Domain.Entities.Profile", "Profile")
                        .WithMany("FavoriteDrugs")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("DrugStore");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.Profile", b =>
                {
                    b.OwnsOne("DrugsBot.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Email");
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.Country", b =>
                {
                    b.Navigation("Drugs");
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.Drug", b =>
                {
                    b.Navigation("DrugItems");
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.DrugStore", b =>
                {
                    b.Navigation("DrugItems");
                });

            modelBuilder.Entity("DrugsBot.Domain.Entities.Profile", b =>
                {
                    b.Navigation("FavoriteDrugs");
                });
#pragma warning restore 612, 618
        }
    }
}
